[package]
name = "tau"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.17.10"
glib = "0.17.10"
gtk4 = "0.7.3"
gtk4-layer-shell = "0.2.0"
regex = "1.10.4"
winit = "0.28.6"
xdg = "2.5.0"

[dependencies.uuid]
version = "1.6.1"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
]
